
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/msys64/mingw64/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "C:/msys64/mingw64/share/cmake/Modules/CMakeMinGWFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:2 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "mingw32-make.exe"
    candidate_directories:
      - "C:/Users/hjard/AppData/Local/Programs/cursor/resources/app/resources/helpers/"
      - "C:/Python313/Scripts/"
      - "C:/Python313/"
      - "C:/Program Files (x86)/Common Files/Oracle/Java/java8path/"
      - "C:/Program Files (x86)/Common Files/Oracle/Java/javapath/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Program Files/dotnet/"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA app/NvDLISR/"
      - "C:/Program Files/Git/cmd/"
      - "C:/ProgramData/chocolatey/bin/"
      - "C:/Program Files/CMake/bin/"
      - "C:/Program Files/nodejs/"
      - "C:/Program Files/Docker/Docker/resources/bin/"
      - "C:/Users/hjard/AppData/Local/Programs/cursor/resources/app/codeBin/"
      - "C:/Users/hjard/AppData/Local/Microsoft/WindowsApps/"
      - "C:/mingw-w64/bin/"
      - "C:/Users/hjard/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "C:/Users/hjard/AppData/Local/Programs/cursor/resources/app/bin/"
      - "C:/Users/SEU_USER/AppData/Local/Programs/Ollama/"
      - "C:/Users/hjard/AppData/Local/Programs/Ollama/"
      - "C:/msys64/mingw64/bin/"
      - "C:/Users/hjard/.bun/bin/"
      - "C:/Users/hjard/AppData/Roaming/npm/"
      - "/REGISTRY-NOTFOUND/bin/"
      - "c:/MinGW/bin/"
      - "/MinGW/bin/"
      - "/REGISTRY-NOTFOUND/MinGW/bin/"
    searched_directories:
      - "C:/Users/hjard/AppData/Local/Programs/cursor/resources/app/resources/helpers/mingw32-make.exe.com"
      - "C:/Users/hjard/AppData/Local/Programs/cursor/resources/app/resources/helpers/mingw32-make.exe"
      - "C:/Python313/Scripts/mingw32-make.exe.com"
      - "C:/Python313/Scripts/mingw32-make.exe"
      - "C:/Python313/mingw32-make.exe.com"
      - "C:/Python313/mingw32-make.exe"
      - "C:/Program Files (x86)/Common Files/Oracle/Java/java8path/mingw32-make.exe.com"
      - "C:/Program Files (x86)/Common Files/Oracle/Java/java8path/mingw32-make.exe"
      - "C:/Program Files (x86)/Common Files/Oracle/Java/javapath/mingw32-make.exe.com"
      - "C:/Program Files (x86)/Common Files/Oracle/Java/javapath/mingw32-make.exe"
      - "C:/Windows/System32/mingw32-make.exe.com"
      - "C:/Windows/System32/mingw32-make.exe"
      - "C:/Windows/mingw32-make.exe.com"
      - "C:/Windows/mingw32-make.exe"
      - "C:/Windows/System32/wbem/mingw32-make.exe.com"
      - "C:/Windows/System32/wbem/mingw32-make.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/mingw32-make.exe.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/mingw32-make.exe"
      - "C:/Windows/System32/OpenSSH/mingw32-make.exe.com"
      - "C:/Windows/System32/OpenSSH/mingw32-make.exe"
      - "C:/Program Files/dotnet/mingw32-make.exe.com"
      - "C:/Program Files/dotnet/mingw32-make.exe"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/mingw32-make.exe.com"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/mingw32-make.exe"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA app/NvDLISR/mingw32-make.exe.com"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA app/NvDLISR/mingw32-make.exe"
      - "C:/Program Files/Git/cmd/mingw32-make.exe.com"
      - "C:/Program Files/Git/cmd/mingw32-make.exe"
      - "C:/ProgramData/chocolatey/bin/mingw32-make.exe.com"
      - "C:/ProgramData/chocolatey/bin/mingw32-make.exe"
      - "C:/Program Files/CMake/bin/mingw32-make.exe.com"
      - "C:/Program Files/CMake/bin/mingw32-make.exe"
      - "C:/Program Files/nodejs/mingw32-make.exe.com"
      - "C:/Program Files/nodejs/mingw32-make.exe"
      - "C:/Program Files/Docker/Docker/resources/bin/mingw32-make.exe.com"
      - "C:/Program Files/Docker/Docker/resources/bin/mingw32-make.exe"
      - "C:/Users/hjard/AppData/Local/Programs/cursor/resources/app/codeBin/mingw32-make.exe.com"
      - "C:/Users/hjard/AppData/Local/Programs/cursor/resources/app/codeBin/mingw32-make.exe"
      - "C:/Users/hjard/AppData/Local/Microsoft/WindowsApps/mingw32-make.exe.com"
      - "C:/Users/hjard/AppData/Local/Microsoft/WindowsApps/mingw32-make.exe"
      - "C:/mingw-w64/bin/mingw32-make.exe.com"
      - "C:/mingw-w64/bin/mingw32-make.exe"
      - "C:/Users/hjard/AppData/Local/Programs/Microsoft VS Code/bin/mingw32-make.exe.com"
      - "C:/Users/hjard/AppData/Local/Programs/Microsoft VS Code/bin/mingw32-make.exe"
      - "C:/Users/hjard/AppData/Local/Programs/cursor/resources/app/bin/mingw32-make.exe.com"
      - "C:/Users/hjard/AppData/Local/Programs/cursor/resources/app/bin/mingw32-make.exe"
      - "C:/Users/SEU_USER/AppData/Local/Programs/Ollama/mingw32-make.exe.com"
      - "C:/Users/SEU_USER/AppData/Local/Programs/Ollama/mingw32-make.exe"
      - "C:/Users/hjard/AppData/Local/Programs/Ollama/mingw32-make.exe.com"
      - "C:/Users/hjard/AppData/Local/Programs/Ollama/mingw32-make.exe"
      - "C:/msys64/mingw64/bin/mingw32-make.exe.com"
      - "C:/msys64/mingw64/bin/mingw32-make.exe"
      - "C:/Users/hjard/.bun/bin/mingw32-make.exe.com"
      - "C:/Users/hjard/.bun/bin/mingw32-make.exe"
      - "C:/Users/hjard/AppData/Roaming/npm/mingw32-make.exe.com"
      - "C:/Users/hjard/AppData/Roaming/npm/mingw32-make.exe"
      - "/REGISTRY-NOTFOUND/bin/mingw32-make.exe.com"
      - "/REGISTRY-NOTFOUND/bin/mingw32-make.exe"
      - "c:/MinGW/bin/mingw32-make.exe.com"
      - "c:/MinGW/bin/mingw32-make.exe"
      - "/MinGW/bin/mingw32-make.exe.com"
      - "/MinGW/bin/mingw32-make.exe"
      - "/REGISTRY-NOTFOUND/MinGW/bin/mingw32-make.exe.com"
      - "/REGISTRY-NOTFOUND/MinGW/bin/mingw32-make.exe"
    found: false
    search_context:
      ENV{PATH}:
        - "c:\\Users\\hjard\\AppData\\Local\\Programs\\cursor\\resources\\app\\resources\\helpers"
        - "C:\\Python313\\Scripts\\"
        - "C:\\Python313\\"
        - "C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\java8path"
        - "C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files\\dotnet\\"
        - "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common"
        - "C:\\Program Files\\NVIDIA Corporation\\NVIDIA app\\NvDLISR"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\ProgramData\\chocolatey\\bin"
        - "C:\\Program Files\\CMake\\bin"
        - "C:\\Program Files\\nodejs\\"
        - "C:\\Program Files\\Docker\\Docker\\resources\\bin"
        - "c:\\Users\\hjard\\AppData\\Local\\Programs\\cursor\\resources\\app\\codeBin"
        - "C:\\Python313\\Scripts\\"
        - "C:\\Python313\\"
        - "C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\java8path"
        - "C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files\\dotnet\\"
        - "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common"
        - "C:\\Program Files\\NVIDIA Corporation\\NVIDIA app\\NvDLISR"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\ProgramData\\chocolatey\\bin"
        - "C:\\Program Files\\nodejs\\"
        - "C:\\Python313\\Scripts\\"
        - "C:\\Python313\\"
        - "C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\java8path"
        - "C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files\\dotnet\\"
        - "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common"
        - "C:\\Program Files\\NVIDIA Corporation\\NVIDIA app\\NvDLISR"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\ProgramData\\chocolatey\\bin"
        - "C:\\Program Files\\nodejs\\"
        - "C:\\Users\\hjard\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\mingw-w64\\bin"
        - "C:\\Users\\hjard\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\Users\\hjard\\AppData\\Local\\Programs\\cursor\\resources\\app\\bin"
        - "C:\\Users\\SEU_USER\\AppData\\Local\\Programs\\Ollama"
        - "C:\\Users\\hjard\\AppData\\Local\\Programs\\Ollama"
        - "C:\\msys64\\mingw64\\bin"
        - "C:\\Users\\hjard\\.bun\\bin"
        - "C:\\Users\\hjard\\AppData\\Roaming\\npm"
...
